resize:
  max_width: 800
  max_height: 600

deskew:
  gaussian_blur_kernel: [5, 5]
  canny_threshold1: 50
  canny_threshold2: 150
  hough_threshold: 200
  median_angle_range: [-15, 15]
  min_angle_threshold: 2

preprocess:
  morph_kernel_size: [3, 3]
  adaptive_thresh_block_size: 35
  adaptive_thresh_C: 10

extract_answers:
  num_columns: 4
  num_questions: 25
  num_choices: 5
  threshold: 0.3

extract_student_number:
  num_digits: 11
  num_options: 10
  threshold: 0.35

extract_test_group:
  groups: ['A', 'B', 'C', 'D']
  min_contour_area: 30  
  threshold: 0.1        
  dominance_threshold: 0.02 

dynamic_roi:
  answer_heading_text: "CEVAPLAR"
  answer_heading_min_text_length: 7
  answer_heading_max_text_length: 15
  answer_area:
    offset_x: -230
    offset_y: 74
    width: 610
    height: 572
    extra_width: 0
    extra_height: 0

  student_number_heading_text: "ÖĞRENCİ NUMARASI"
  student_number_heading_min_text_length: 10
  student_number_heading_max_text_length: 20
  student_number_area:
    offset_x: -60
    offset_y: 53
    width: 255
    height: 230
    extra_width: 0
    extra_height: 0

  test_group_heading_text: "TEST GRUBU"
  test_group_heading_min_text_length: 8
  test_group_heading_max_text_length: 10
  test_group_area:
    offset_x: 133
    offset_y: -20
    width: 170
    height: 42
    extra_width: 0
    extra_height: 0

  answer_key_heading_text: "CEVAP ANAHTARI"
  answer_key_heading_min_text_length: 6
  answer_key_heading_max_text_length: 15
  answer_key_area:
    offset_x: -230
    offset_y: 74
    width: 610
    height: 572
    extra_width: 0
    extra_height: 0

template_matching:
  template_path: "omr_app/template.jpg"
  threshold: 0.8

feature_matching:
  min_matches: 10

ocr:
  language: "tur"
  detect_orientation: True
  similarity_threshold: 60
  min_text_length: 3
  max_text_length: 100

output:
  save_debug_images: True
  save_visualization: True
  visualization_directory: "visualizations"
  debug_images_directory: "debug_images"
  save_rois: True
  rois_directory: "rois"
  save_results_json: False
  results_json_path: "results/results.yaml"

logging:
  level: "INFO"
  log_file: "logs/omr_processing.log"
